const CONSTANTS_MESSAGES = {
  USER_EXISTS: "User already exists",
  USER_INACTIVE: "User inactive. Contact OPD Sure for reactivation",
  INTERNAL_SERVER_ERROR: "Something went wrong. Please try again",
  SUCCESS: "API executed successfully",
  USER_NOT_FOUND: "User not found in database ",
  SPECIALIZATION_NOT_FOUND: "Specialization does not exists in database ",
  ID_NOT_FOUND: "Id not found in database",
  CORPORATE_NOT_FOUND: "Corporate not found in database",
  WRONG_PASSWORD: "Wrong password entered",
  EMAIL_EXISTS: "Email already registered",
  MOBILE_EXISTS: "Mobile already registered",
  HR_FOR_COMPANT_EXISTS: "HR already registered for company",
  COUPON_CODE_EXISTS: "Coupon code already exists",
  PERMISSION_UPDATE_FAILED: "Failed to update permissions",
  BULK_UPLOAD_FAILED: "Bulk Upload failed",
  DOC_REGNO_EXISTS: "Doctor's registration number already exists",
  NAME_EXISTS: "Name already exists",
  CHECKUP_CODE_EXISTS: "Health Checkup code already exists",
  CHECKUP_PLAN_NOT_EXISTS: "Health Checkup plain does not exists",
  CANNOT_DOWNGRADE_PLAN: "Plan cannot be downgraded",
  INVALID_TOKEN: "Invalid jwt token",
  ADMIN_NOT_FOUND: "Admin not found in database",
  ADMIN_INACTIVE: "Admin is inactive",
  MANAGEMENT_USER_NOT_FOUND: "Management user not found in database",
  MANAGEMENT_USER_HAS_ASSIGNED_CLAIMS: "Management user has assigned claims",
  MANAGEMENT_USER_INACTIVE: "Management user is inactive",
  INVALID_PASSWORD: "Password must contains 1 Uppercase 1 Number and 1 Special Character with length at least 8",
  UNAUTHORIZED: "Not authorized.",
  TOKEN_NOT_FOUND: "Token not found",
  OLD_NEW_PASSWORD_ERROR: "New password can't be same as old password",
  MEMBER_NOT_FOUND: "Family member not found",
  MEMBER_DELETE_ERROR: "Approval request is under process, can't delete member",
  FAILED_TO_UPDATE_CLAIM_STATUS: "Failed to update claim status",
  CLAIM_ALREADY_APPROVED: "Claim already approved",
  ACTION_ALREADY_TAKEN: "Action on claim already taken",
  FAMILY_MEMBER_NOT_FOUND: "User not found",
  ACTION_ALREADY_TAKEN: "Action already taken",
  CANNOT_ADD_MAIN_MEMBER: "Account owner cannot be added",
  CANNOT_EDIT_MAIN_MEMBER: "Account owner status cannot be changed",
  PLAN_EXPIRED: "Account owner status cannot be changed",
  PLAN_EXPIRED_CANNOT_RENEW: "Plan is already expired cannot renew form profile",
  PAID_MEMBER_LIST_FULL: "Max limit for paid members reached for subscribed plan",
  FAMILY_MEMBER_UPDATE_PENDING: "Family member update pending",
  DISPUTE_ALREADY_RAISED: "Dispute already raised on claim",
  DISPUTE_CANNOT_BE_RAISED: "Dispute cannot be raised as claim is under process",
  CLAIM_ALREADY_REJECTED: "Claim already rejected",
  INVALID_COUPON_CODE: "Invalid coupon code",
  NOT_VALID_FOR_RETAIL_USERS: "Coupon code invalid for retail users",
  NOT_VALID_FOR_CORPORATE_USERS: "Coupon code invalid for corporate users",
  NOT_VALID_FOR_THIS_CORPORATE: "Coupon code invalid for your company",
  EXCEEDED_MAX_ALLOWED_USAGE: "Exceeded maximum allowed usage",
  COUPON_ALREADY_USED: "Coupon code already used",
  EXPIRED_COUPON_CODE: "Validity expired for coupon code",
  PLAN_EXPIRED_UPGRADE: "Plan cannot be upgraded. Plan already expired.",
  MEMBER_DELETE_ERROR: "Approval request is under process, can't delete member",
  MEMBER_CANNOT_DELETE_ERROR: "Member can not be delete",
  CLAIM_NOT_FOUND: "Claim not found.",
  FORGOT_PASSWORD: "Link sent on your mail",
  CONFLICT_SELF: "Main user can not be repeated",
  NEGATIVE_AMOUNT: "Amount cannot be negative",
  MEMBER_LIMIT: "Family members can't be more than 10",
  PLAN_NOT_FOUND: "Plan doesn't exist.",
  EMAIL_TEMPLATE_NOT_FOUND : "Email template not found",
  CLAIM_NOT_APPROVED: "Claim not appoved from finance",
  VERIFIER_NOT_FOUND: "Verifier not found.",
  VERIFIER_NOT_TRANSFERABLE: "Only pending and clarification claims can be transfered",
  INSUFFICIENT_BALANCE: "Insufficient wallet balance",
  CANNOT_DELETE_USER_CLAIM_RAISED: " Cannot delete user as  claim is already raised by user."
}

module.exports = CONSTANTS_MESSAGES;
